const data = [
  { name: 'Factorial', mark: '!', key: '1' },
  { name: 'Open parenthesis', mark: '(', key: '2' },
  { name: 'Close parenthesis', mark: ')', key: '3' },
  { name: 'Remainder of division', mark: '%', key: '4' },
  { name: 'Delete', mark: 'CD', key: '5' },
  { name: 'Natural logarithm', mark: 'ln', key: '6' },
  { name: '7', mark: '7', key: '7' },
  { name: '8', mark: '8', key: '8' },
  { name: '9', mark: '9', key: '9' },
  { name: 'Division', mark: '÷', key: '10' },
  { name: 'Logarithm', mark: 'log', key: '11' },
  { name: '4', mark: '4', key: '12' },
  { name: '5', mark: '5', key: '13' },
  { name: '6', mark: '6', key: '14' },
  { name: 'Multiplication', mark: '×', key: '15' },
  { name: 'Root', mark: '√', key: '16' },
  { name: '1', mark: '1', key: '17' },
  { name: '2', mark: '2', key: '18' },
  { name: '3', mark: '3', key: '19' },
  { name: 'Difference', mark: '-', key: '20' },
  { name: 'Exponentiation', mark: '^', key: '21' },
  { name: '0', mark: '0', key: '22' },
  { name: 'Decimal point', mark: '.', key: '23' },
  { name: 'Equal', mark: '=', key: '24' },
  { name: 'Sum', mark: '+', key: '25' },
];

export default data;
